### ISSUE TITLE
Set the user agent

### ISSUE THREAD

**Issue by everett-toews** [mitchellh/vagrant-rackspace#137]
If possible, set the user agent header to be prepended with `vagrant/{version}` so we know when and how Vagrant is being used on Rackspace.

**Comment by ghost** [comment]
Did you ever figure this out?

**Comment by etoews** [comment]
Nope.

**Comment by ghost** [comment]
Here is a pull request I made to Vagrant that might fix your issue. Simple set the VAGRANT_USER_AGENT env var to what you want, and it should do the rest. We tested it and it works for my team.

https://github.com/mitchellh/vagrant/pull/8386
