### ISSUE TITLE
README Error Regarding Networks

### ISSUE THREAD

**Issue by derks** [mitchellh/vagrant-rackspace#145]
The README references `rs.network = 'some-network-uuid'`:
- https://github.com/mitchellh/vagrant-rackspace/blob/master/README.md#networks

However this throws the error:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

RackSpace Provider:
* The following settings shouldn't exist: network
```

Looking at the code:
- https://github.com/mitchellh/vagrant-rackspace/blob/master/lib/vagrant-rackspace/config.rb#L170

It appears this should actually be `rs.networks` and takes an Array:

``` ruby
rs.networks = [
  'some-network-uuid',
  'some-other-network-uuid',
]
```

**Comment by derks** [comment]
I was going to make a pull-request, but realized that I do not know how the situation is (or isn't) handled regarding:

``` ruby
rs.network :service_net, :attached => false
```

?

FWIW, using the following **did** attached the cloud network in question:

``` ruby
rs.networks = [
  'some-network-uuid',
  'some-other-network-uuid',
]
```

**Comment by derks** [comment]
Sorry... BIG CORRECTION:

Using the above infact does not work... unless I specify all networks including `PublicNet` and `ServiceNet`.  The box I just built only had my custom network, and no `PrivateNet`/`ServiceNet`.  This does work:

``` ruby
rs.networks = [
  '00000000-0000-0000-0000-000000000000',
  '11111111-1111-1111-1111-111111111111',
  'some-network-uuid',
]
```

Apologies for all the noise.

**Comment by DavidWittman** [comment]
@derks Here's the example directly from the README:

``` ruby
config.vm.provider :rackspace do |rs|
  rs.username = ENV['RAX_USERNAME']
  rs.api_key  = ENV['RAX_API_KEY']
  rs.network '443aff42-be57-effb-ad30-c097c1e4503f'
  rs.network '5e738e11-def2-4a75-ad1e-05bbe3b49efe'
  rs.network :service_net, :attached => false
end
```

Notice that `rs.network` is calling a method and not setting a value with `=`. This is akin to using the Virtualbox provider and defining additional networks. Behind the scenes this just manipulates the `rs.networks` attribute, which you've found that you can define directly from the provider config as well.

**Comment by derks** [comment]
Of course!  Not the first time this oversight has bit me in the ass.  Many apologies for the noise, and thanks for the quick response.
