### ISSUE TITLE
how to specify on which of the rackspace cloud servers vagrant should deploy the VMs?

### ISSUE THREAD

**Issue by noeliaoses** [mitchellh/vagrant-rackspace#146]
Hi,

I have a vagrantfile to create several VMS. I also have several rackspace cloud servers. How can I specify in the vagrantfile on which of the cloud servers each VM should go?

Thank you very much for your help!
Noelia

**Comment by derks** [comment]
@noeliaoses Vagrant, and the Vagrant Rackspace Plugin, are used to create/provision VMs on Rackspace.  There aren't any means of provisioning new VMs onto existing servers in Rackspace.  When you run `vagrant up`, that will create new servers in Rackspace based on what is defined by your Vagrantfile.

**Comment by noeliaoses** [comment]
@derks  Thank you for clarifying that!!! I appreciate all your help very much
